# -*- coding: utf-8 -*-
"""
RL training data format converter.

Functionality:
  1. Read raw trajectory data generated by data_builder.py
  2. Convert to multiple training framework formats:
     - LLaMA-Factory SFT format (instruction / input / output)
     - GRPO reinforcement learning format (prompt / completion)
     - ShareGPT conversation format (messages list)
  3. Validate trajectory integrity (tag closure, answer non-empty)
  4. Support multi-file merging and deduplication

Usage:
  # Convert to all formats (default)
  python app/rl/format_converter.py

  # Generate SFT format only
  python app/rl/format_converter.py --format sft

  # Generate GRPO format only
  python app/rl/format_converter.py --format grpo

  # Specify input file
  python app/rl/format_converter.py --input data/rl_data/web_fallback_trajectories.json

  # Merge multiple trajectory files then convert
  python app/rl/format_converter.py --input a.json b.json --merge
"""

import os
import re
import json
import argparse
import logging
import hashlib
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# ── Project root ──────────────────────────────────────────────
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# ── Default paths ──────────────────────────────────────────────
DEFAULT_INPUT  = os.path.join(BASE_DIR, "data/rl_data/web_fallback_trajectories.json")
DEFAULT_OUTPUT = os.path.join(BASE_DIR, "data/rl_data")

# ── System prompt (consistent with data_builder.py) ───────────
SYSTEM_PROMPT = """你是小米SU7车型的专业问答助手，服务范围严格限定在小米SU7相关问题。

回答问题时可以调用以下工具：
- 本地知识库检索（优先）：<search_local>检索关键词</search_local>
- 网络搜索（本地信息不足时）：<search_web>检索关键词</search_web>
- 页面深度阅读（搜索结果不够详细时）：<read_page>URL地址</read_page>

工具返回格式：<information>检索结果内容</information>

最终答案格式：<answer>答案内容</answer>

注意：
1. 优先调用本地知识库，本地无结果或信息严重不足时再调用网络搜索
2. 网络搜索结果中包含"网址："字段，可选择最有价值的页面用 <read_page> 深入阅读，最多读取2个页面
3. 与小米SU7无关的问题（闲聊、百科、娱乐等），直接输出 <answer>很抱歉，我只能回答小米SU7相关问题。</answer>
4. 网络搜索结果来源于互联网，答案中需注明"根据网络信息"
5. 涉及页码引用时格式为【页码】"""

# ── Tag regex patterns ────────────────────────────────────────
_RE_ANSWER       = re.compile(r"<answer>(.*?)</answer>",            re.DOTALL)
_RE_SEARCH_LOCAL = re.compile(r"<search_local>(.*?)</search_local>", re.DOTALL)
_RE_SEARCH_WEB   = re.compile(r"<search_web>(.*?)</search_web>",   re.DOTALL)
_RE_READ_PAGE    = re.compile(r"<read_page>(.*?)</read_page>",     re.DOTALL)
_RE_INFORMATION  = re.compile(r"<information>(.*?)</information>",  re.DOTALL)


# ────────────────────────────────────────────────────────────
# Trajectory validation
# ────────────────────────────────────────────────────────────

def validate_trajectory(trajectory: str) -> dict:
    """
    Validate a single trajectory's integrity, returning a report.

    Returns:
        {
            "valid":        bool,
            "has_answer":   bool,
            "has_search":   bool,
            "has_read_page": bool,
            "answer_empty": bool,
            "errors":       list[str],
        }
    """
    errors = []
    has_answer    = bool(_RE_ANSWER.search(trajectory))
    has_local     = bool(_RE_SEARCH_LOCAL.search(trajectory))
    has_web       = bool(_RE_SEARCH_WEB.search(trajectory))
    has_read_page = bool(_RE_READ_PAGE.search(trajectory))
    has_info      = bool(_RE_INFORMATION.search(trajectory))
    has_search    = has_local or has_web

    if not has_answer:
        errors.append("缺少 <answer>...</answer> 标签")

    if not has_search:
        errors.append("缺少搜索调用标签（<search_local> 或 <search_web>）")

    if has_search and not has_info:
        errors.append("存在搜索调用但缺少 <information> 响应")

    # read_page optional validation: check closure and URL format when present
    if has_read_page:
        opens  = trajectory.count("<read_page>")
        closes = trajectory.count("</read_page>")
        if opens != closes:
            errors.append(f"<read_page> 标签不匹配（{opens}开 / {closes}闭）")
        # Check URL format
        for url in _RE_READ_PAGE.findall(trajectory):
            url = url.strip()
            if not url.startswith(("http://", "https://")):
                errors.append(f"<read_page> URL 格式无效：{url[:60]}")

    # Check if answer content is empty
    answer_empty = False
    if has_answer:
        answer_text = _RE_ANSWER.search(trajectory).group(1).strip()
        if not answer_text:
            errors.append("<answer> 内容为空")
            answer_empty = True

    return {
        "valid":         len(errors) == 0,
        "has_answer":    has_answer,
        "has_search":    has_search,
        "has_read_page": has_read_page,
        "answer_empty":  answer_empty,
        "errors":        errors,
    }


def extract_answer(trajectory: str) -> str:
    """Extract plain answer text from a trajectory."""
    match = _RE_ANSWER.search(trajectory)
    return match.group(1).strip() if match else ""


def to_sft_target(trajectory: str) -> str:
    """
    Construct the SFT warm-up supervision target.

    SFT only learns tool-call decisions and final answer;
    <information> blocks are environment/tool returns — the model
    should NOT be required to recite retrieval results in its
    assistant output.
    """
    target = _RE_INFORMATION.sub("", trajectory)
    target = re.sub(r"\n{3,}", "\n\n", target)
    return target.strip()


# ────────────────────────────────────────────────────────────
# Format conversion functions
# ────────────────────────────────────────────────────────────

def to_sft_format(
    question:    str,
    trajectory:  str,
    system:      str  = SYSTEM_PROMPT,
    data_source: str  = "web_fallback",
    **kwargs,
) -> dict:
    """
    Convert to LLaMA-Factory SFT format.

    Fields:
      instruction: User question
      input:       Empty (question already in instruction)
      output:      Lightweight trajectory without <information> (as training target)
      system:      System prompt
      data_source: Data source identifier ("web_fallback" / "local_only")
    """
    answer_text = extract_answer(trajectory)
    return {
        "instruction": question,
        "input":       "",
        "output":      to_sft_target(trajectory),
        "answer":      answer_text,
        "system":      system,
        "data_source": data_source,
    }


def to_grpo_format(
    question:    str,
    trajectory:  str,
    category:    str  = "",
    system:      str  = SYSTEM_PROMPT,
    data_source: str  = "web_fallback",
    reward_type: str  = "web_answer_quality",
) -> dict:
    """
    Convert to GRPO training format.

    prompt:     system + user message list
    completion: assistant trajectory text
    answer:     plain answer text (for reward computation)
    """
    answer_text = extract_answer(trajectory)
    return {
        "prompt": [
            {"role": "system", "content": system},
            {"role": "user",   "content": question},
        ],
        "completion":  trajectory,
        "answer":      answer_text,
        "category":    category,
        "data_source": data_source,
        "reward_type": reward_type,
    }


def to_sharegpt_format(
    question:   str,
    trajectory: str,
    system:     str = SYSTEM_PROMPT,
    **kwargs,
) -> dict:
    """
    Convert to ShareGPT multi-turn conversation format.

    Messages list contains system -> user -> assistant three turns,
    suitable for training frameworks supporting conversation format.
    """
    return {
        "messages": [
            {"role": "system",    "content": system},
            {"role": "user",      "content": question},
            {"role": "assistant", "content": trajectory},
        ],
        "data_source": "web_fallback",
    }


# ── Format registry ──────────────────────────────────────────
FORMAT_REGISTRY = {
    "sft":      {"converter": to_sft_format,      "ext": "_sft.json",    "is_jsonl": False},
    "grpo":     {"converter": to_grpo_format,      "ext": "_grpo.jsonl",  "is_jsonl": True},
    "sharegpt": {"converter": to_sharegpt_format,  "ext": "_sharegpt.json", "is_jsonl": False},
}


# ────────────────────────────────────────────────────────────
# Data loading & merging
# ────────────────────────────────────────────────────────────

def load_trajectories(path: str) -> list[dict]:
    """Load a single trajectory JSON file."""
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, list):
        data = [data]
    return data


def merge_files(paths: list[str], dedup: bool = True) -> list[dict]:
    """
    Merge multiple trajectory files, optionally deduplicating by question.

    Dedup strategy: same question -> keep latest (later-loaded overwrites earlier).
    """
    all_data: list[dict] = []
    for p in paths:
        all_data.extend(load_trajectories(p))

    if not dedup:
        return all_data

    seen: dict[str, dict] = {}
    for item in all_data:
        question = item.get("question", "")
        key = hashlib.md5(question.encode("utf-8")).hexdigest()
        seen[key] = item  # later overwrites earlier

    return list(seen.values())


# ────────────────────────────────────────────────────────────
# Core conversion pipeline
# ────────────────────────────────────────────────────────────

def repair_trajectory(trajectory: str) -> tuple[str, list[str]]:
    """
    Repair common formatting issues (e.g. LLM output truncated by max_tokens,
    leaving closing tags missing).

    Returns:
        (repaired_trajectory, list_of_fixes)
    """
    fixes = []

    # Fix: <answer> open tag present but close tag missing (most common truncation)
    if "<answer>" in trajectory and "</answer>" not in trajectory:
        trajectory += "</answer>"
        fixes.append("补齐 </answer> 闭标签")

    return trajectory, fixes


def convert(
    data:         list[dict],
    target_format: str  = "all",
    skip_invalid:  bool = True,
) -> dict[str, list[dict]]:
    """
    Batch convert trajectory data.

    Args:
        data:          Raw trajectory data list
        target_format: "all" | "sft" | "grpo" | "sharegpt"
        skip_invalid:  Whether to skip validation-failed trajectories

    Returns:
        {format_name: [converted_items]}
    """
    # Determine which formats to generate
    if target_format == "all":
        formats = list(FORMAT_REGISTRY.keys())
    else:
        formats = [target_format]

    # Preprocessing: auto-repair + validate + filter
    repair_count = 0
    valid_items = []
    for item in data:
        trajectory = item.get("trajectory", "")

        # Auto-repair known format issues
        trajectory, fixes = repair_trajectory(trajectory)
        if fixes:
            item["trajectory"] = trajectory
            q = item.get("question", "")[:30]
            logger.info("  [FIX] %s... -> %s", q, fixes)
            repair_count += 1

        report = validate_trajectory(trajectory)

        if not report["valid"]:
            q = item.get("question", "")[:30]
            if skip_invalid:
                logger.info("  [SKIP] Trajectory incomplete: %s... -> %s", q, report["errors"])
                continue
            else:
                logger.warning("  [WARN] Trajectory incomplete but kept: %s... -> %s", q, report["errors"])

        valid_items.append(item)

    if repair_count:
        logger.info("[INFO] Auto-repaired: %d items", repair_count)
    logger.info("[INFO] Valid trajectories: %d/%d", len(valid_items), len(data))

    # Per-format conversion
    results: dict[str, list[dict]] = {}
    for fmt in formats:
        if fmt not in FORMAT_REGISTRY:
            logger.warning("[WARN] Unknown format '%s', skipped", fmt)
            continue

        converter_fn = FORMAT_REGISTRY[fmt]["converter"]
        converted = []
        for item in valid_items:
            try:
                converted.append(converter_fn(
                    question   = item.get("question", ""),
                    trajectory = item.get("trajectory", ""),
                    category   = item.get("category", ""),
                ))
            except Exception as e:
                q = item.get("question", "")[:30]
                logger.error("  [ERROR] Conversion failed (%s): %s... -> %s", fmt, q, e)

        results[fmt] = converted
        logger.info("[INFO] %s format: %d items", fmt, len(converted))

    return results


def save(
    results:     dict[str, list[dict]],
    output_dir:  str           = DEFAULT_OUTPUT,
    base_name:   str           = "web_fallback_trajectories",
) -> list[str]:
    """
    Write conversion results to files.

    Returns:
        List of written file paths
    """
    os.makedirs(output_dir, exist_ok=True)
    written = []

    for fmt, items in results.items():
        if not items:
            continue

        cfg  = FORMAT_REGISTRY[fmt]
        path = os.path.join(output_dir, base_name + cfg["ext"])

        with open(path, "w", encoding="utf-8") as f:
            if cfg["is_jsonl"]:
                for item in items:
                    f.write(json.dumps(item, ensure_ascii=False) + "\n")
            else:
                json.dump(items, f, ensure_ascii=False, indent=2)

        written.append(path)
        logger.info("  [SAVE] %s (%d items)", path, len(items))

    return written


# ────────────────────────────────────────────────────────────
# Statistics report
# ────────────────────────────────────────────────────────────

def print_report(data: list[dict]):
    """Print category statistics for trajectory data."""
    total = len(data)
    if total == 0:
        print("No data.")
        return

    # Category stats
    cat_counts: dict[str, int] = {}
    web_count   = 0
    answer_lens = []

    for item in data:
        cat = item.get("category_zh") or item.get("category", "其他")
        cat_counts[cat] = cat_counts.get(cat, 0) + 1

        if item.get("web_search_used"):
            web_count += 1

        answer = extract_answer(item.get("trajectory", ""))
        if answer:
            answer_lens.append(len(answer))

    avg_len = sum(answer_lens) / len(answer_lens) if answer_lens else 0

    print("\n" + "=" * 60)
    print("Format Conversion Report")
    print("=" * 60)
    print(f"Total: {total} items")
    print(f"Web fallback: {web_count} items ({web_count / total * 100:.1f}%)")
    print(f"Average answer length: {avg_len:.0f} chars")
    print(f"\nCategory distribution:")
    for cat, cnt in sorted(cat_counts.items(), key=lambda x: -x[1]):
        print(f"  {cat}: {cnt} items")
    print("=" * 60)


# ────────────────────────────────────────────────────────────
# CLI entry
# ────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="RL training data format converter")
    parser.add_argument(
        "--input", nargs="+", default=[DEFAULT_INPUT],
        help="Input trajectory JSON file path(s) (supports multiple files)",
    )
    parser.add_argument(
        "--output-dir", default=DEFAULT_OUTPUT,
        help="Output directory (default data/rl_data/)",
    )
    parser.add_argument(
        "--format", dest="target_format", default="all",
        choices=["all", "sft", "grpo", "sharegpt"],
        help="Target format (default all)",
    )
    parser.add_argument(
        "--merge", action="store_true",
        help="Merge multiple input files and deduplicate by question",
    )
    parser.add_argument(
        "--keep-invalid", action="store_true",
        help="Keep validation-failed trajectories (default skip)",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Validate and report only, do not write files",
    )
    args = parser.parse_args()

    # ── Load data ──────────────────────────────────────────
    print(f"[INFO] Loading data: {args.input}")
    if args.merge and len(args.input) > 1:
        data = merge_files(args.input, dedup=True)
        print(f"[INFO] After merge + dedup: {len(data)} items")
    else:
        data = []
        for p in args.input:
            data.extend(load_trajectories(p))
    print(f"[INFO] Total loaded: {len(data)} trajectories")

    # ── Validate + Convert ────────────────────────────────
    results = convert(data, target_format=args.target_format, skip_invalid=not args.keep_invalid)

    # ── Statistics report ──────────────────────────────────
    print_report(data)

    # ── Write files ────────────────────────────────────────
    if args.dry_run:
        print("\n[DRY-RUN] No files written")
    else:
        written = save(results, output_dir=args.output_dir)
        print(f"\nWritten {len(written)} file(s)")


if __name__ == "__main__":
    main()
